version: '3'

services:
  php-apache:
    build: .
    container_name: apps-mnl
    restart: always
    ports:
      - 81:8000
    volumes:
      - ./eshop:/var/www/html
  database:
    image: mysql:5.7
    container_name: db-server-mnl
    restart: always
    environment:
      - MYSQL_DATABASE=eshop_db
      - MYSQL_ROOT_PASSWORD=root
    expose:
      - '3306'
    ports: #remove on production
      - '3307:3306'
    volumes:
      - ./db-files:/var/lib/mysql